In [1]:
import talib
import yfinance as yf
import pandas as pd
from pandas import Timestamp
import numpy as np

In [2]:
data = yf.download('SLV', start = '2023-01-01', end = '2024-01-01')

[*********************100%%**********************]  1 of 1 completed

In [3]:
data_5m = yf.download('SLV', start = '2023-12-01', end = '2024-01-01', interval = '5m')

[*********************100%%**********************]  1 of 1 completed

In [4]:
print(data['Close']['2023-01-03'])

22.049999237060547

In [5]:
data_15m = yf.download('SLV', start = '2023-12-01', end = '2024-01-01', interval = '15m')
data_30m = yf.download('SLV', start = '2023-12-01', end = '2024-01-01', interval = '30m')
data_1h = yf.download('SLV', start = '2023-12-01', end = '2024-01-01', interval = '1h')

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

In [6]:
data_60m = yf.download('SLV', start = '2023-12-01', end = '2024-01-01', interval = '60m')
pd.set_option('display.max_rows', 141)
data_60m

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2023-12-01 09:30:00,23.090000,23.290001,23.049999,23.154499,23.154499,5500911
2023-12-01 10:30:00,23.150000,23.219999,23.059999,23.190001,23.190001,5008077
2023-12-01 11:30:00,23.184999,23.260000,23.130100,23.240200,23.240200,2358552
2023-12-01 12:30:00,23.240000,23.370001,23.240000,23.271000,23.271000,3498573
2023-12-01 13:30:00,23.270700,23.371201,23.250099,23.315001,23.315001,1951401
2023-12-01 14:30:00,23.320000,23.340000,23.240000,23.339899,23.339899,1304449
2023-12-01 15:30:00,23.338900,23.360001,23.309999,23.330000,23.330000,2141565
2023-12-04 09:30:00,22.750000,22.920000,22.540001,22.639999,22.639999,10700933
2023-12-04 10:30:00,22.635000,22.650000,22.361000,22.400000,22.400000,8776541
2023-12-04 11:30:00,22.400000,22.590000,22.360100,22.495001,22.495001,3404470
2023-12-04 12:30:00,22.490000,22.540001,22.434999,22.450001,22.450001,2696900
2023-12-04 13:30:00,22.445000,22.469999,22.420000,22.455000,22.455000,701290
2023-12-04 14:30:00,22.459999,22.504999,22.440001,22.440001,22.440001,1874846
2023-12-04 15:30:00,22.440001,22.459999,22.420000,22.455000,22.455000,2053581
2023-12-05 09:30:00,22.281000,22.375000,22.090000,22.100000,22.100000,9539784
2023-12-05 10:30:00,22.110001,22.155899,22.010000,22.030001,22.030001,7106310
2023-12-05 11:30:00,22.036600,22.100000,21.950001,22.080000,22.080000,3178337
2023-12-05 12:30:00,22.075001,22.155001,22.059999,22.135000,22.135000,1808895
2023-12-05 13:30:00,22.135000,22.170000,22.090099,22.129999,22.129999,1989254
2023-12-05 14:30:00,22.129999,22.160000,22.100100,22.115000,22.115000,1545197
2023-12-05 15:30:00,22.110001,22.129999,22.110001,22.115000,22.115000,1486444
2023-12-06 09:30:00,22.170000,22.200001,22.010000,22.075100,22.075100,3690143
2023-12-06 10:30:00,22.070499,22.139999,21.980000,21.995001,21.995001,1778784
2023-12-06 11:30:00,22.000000,22.040001,21.889999,21.898300,21.898300,2427187
2023-12-06 12:30:00,21.889999,21.950001,21.868999,21.909000,21.909000,2217449
2023-12-06 13:30:00,21.907101,21.969999,21.900101,21.944201,21.944201,1033762
2023-12-06 14:30:00,21.940001,21.975000,21.930000,21.947500,21.947500,963039
2023-12-06 15:30:00,21.940901,21.950001,21.915001,21.929001,21.929001,1058914
2023-12-07 09:30:00,21.889999,21.910000,21.719999,21.780001,21.780001,5527787
2023-12-07 10:30:00,21.780001,21.840099,21.733700,21.770000,21.770000,2553320
2023-12-07 11:30:00,21.770000,21.770000,21.600000,21.680000,21.680000,2565710
2023-12-07 12:30:00,21.674999,21.777500,21.669201,21.770000,21.770000,2708136
2023-12-07 13:30:00,21.770000,21.830000,21.770000,21.790001,21.790001,1160412
2023-12-07 14:30:00,21.795000,21.815001,21.780001,21.795000,21.795000,917608
2023-12-07 15:30:00,21.795000,21.820000,21.790001,21.799999,21.799999,919280
2023-12-08 09:30:00,21.369900,21.549999,21.299999,21.516199,21.516199,10735981
2023-12-08 10:30:00,21.510000,21.559999,21.180000,21.215000,21.215000,4870895
2023-12-08 11:30:00,21.219999,21.229900,21.030001,21.055401,21.055401,4776528
2023-12-08 12:30:00,21.049999,21.090000,21.014999,21.040001,21.040001,2883433
2023-12-08 13:30:00,21.040001,21.112301,21.040001,21.100201,21.100201,1226928
2023-12-08 14:30:00,21.100000,21.120001,21.080000,21.105000,21.105000,1510789
2023-12-08 15:30:00,21.100000,21.105000,21.080000,21.100000,21.100000,2054275
2023-12-11 09:30:00,20.965000,21.000000,20.812500,20.825001,20.825001,6344446
2023-12-11 10:30:00,20.830000,20.870001,20.820000,20.857700,20.857700,3348662
2023-12-11 11:30:00,20.855000,20.888700,20.809999,20.829901,20.829901,2360644
2023-12-11 12:30:00,20.825001,20.865499,20.809999,20.855000,20.855000,1909277
2023-12-11 13:30:00,20.860001,20.969900,20.860001,20.934999,20.934999,1704097
2023-12-11 14:30:00,20.934999,20.940001,20.900000,20.915001,20.915001,1530852
2023-12-11 15:30:00,20.915001,20.930000,20.910000,20.910000,20.910000,2943752
2023-12-12 09:30:00,20.965000,20.975000,20.820000,20.930099,20.930099,5280767
2023-12-12 10:30:00,20.937201,20.950001,20.820000,20.840000,20.840000,1458726
2023-12-12 11:30:00,20.840099,20.855000,20.780001,20.802500,20.802500,1378737
2023-12-12 12:30:00,20.805000,20.870001,20.790001,20.820000,20.820000,1384849
2023-12-12 13:30:00,20.809999,20.873800,20.790001,20.850000,20.850000,776037
2023-12-12 14:30:00,20.854700,20.870001,20.850000,20.865000,20.865000,725423
2023-12-12 15:30:00,20.869900,20.870001,20.840000,20.840000,20.840000,931991
2023-12-13 09:30:00,20.750000,20.790001,20.612301,20.639900,20.639900,4217571
2023-12-13 10:30:00,20.635000,20.759899,20.620001,20.700001,20.700001,2379294
2023-12-13 11:30:00,20.709999,20.740000,20.670000,20.715000,20.715000,1547459
2023-12-13 12:30:00,20.715000,20.760000,20.709999,20.740000,20.740000,1254775
2023-12-13 13:30:00,20.735001,21.400000,20.709999,21.325001,21.325001,7418601
2023-12-13 14:30:00,21.310101,21.690001,21.309999,21.629999,21.629999,11755407
2023-12-13 15:30:00,21.639999,21.780001,21.634701,21.764999,21.764999,5177733
2023-12-14 09:30:00,22.010000,22.169901,21.990000,22.076200,22.076200,7854133
2023-12-14 10:30:00,22.070000,22.170000,21.990000,22.160000,22.160000,3308775
2023-12-14 11:30:00,22.155100,22.180000,22.120001,22.130100,22.130100,1976872
2023-12-14 12:30:00,22.139999,22.160000,22.030001,22.040001,22.040001,1583785
2023-12-14 13:30:00,22.030001,22.070000,21.990000,22.064699,22.064699,1694956
2023-12-14 14:30:00,22.059999,22.129900,22.049999,22.100000,22.100000,1724928
2023-12-14 15:30:00,22.110001,22.150000,22.110001,22.145000,22.145000,1622799
2023-12-15 09:30:00,21.980000,22.020000,21.889999,21.990000,21.990000,3580989
2023-12-15 10:30:00,21.980000,22.025000,21.930000,22.020000,22.020000,1411692
2023-12-15 11:30:00,22.020000,22.025000,21.940001,21.975000,21.975000,887650
2023-12-15 12:30:00,21.980000,21.980000,21.830000,21.844999,21.844999,1213689
2023-12-15 13:30:00,21.844999,21.879999,21.760000,21.775801,21.775801,1968563
2023-12-15 14:30:00,21.770000,21.850000,21.750000,21.844999,21.844999,1320365
2023-12-15 15:30:00,21.844999,21.865200,21.820000,21.829901,21.829901,1388883
2023-12-18 09:30:00,21.879999,21.879999,21.713900,21.763700,21.763700,3166259
2023-12-18 10:30:00,21.760201,21.825001,21.730000,21.775999,21.775999,768136
2023-12-18 11:30:00,21.775000,21.799999,21.660000,21.684999,21.684999,2772260
2023-12-18 12:30:00,21.688000,21.847099,21.674700,21.764999,21.764999,3089288
2023-12-18 13:30:00,21.761499,21.799999,21.730000,21.785299,21.785299,1524894
2023-12-18 14:30:00,21.780001,21.799999,21.770000,21.790001,21.790001,456248
2023-12-18 15:30:00,21.785000,21.799999,21.770000,21.795000,21.795000,895834
2023-12-19 09:30:00,21.910000,22.120001,21.889999,22.070000,22.070000,4551741
2023-12-19 10:30:00,22.070000,22.129999,22.020000,22.125000,22.125000,2223607
2023-12-19 11:30:00,22.120001,22.125900,22.010000,22.029900,22.029900,1721424
2023-12-19 12:30:00,22.030001,22.040001,21.980101,22.010000,22.010000,1446821
2023-12-19 13:30:00,22.004999,22.040001,22.000000,22.020000,22.020000,421033
2023-12-19 14:30:00,22.010099,22.025000,21.990000,22.010000,22.010000,721020
2023-12-19 15:30:00,22.014999,22.035101,22.010000,22.035101,22.035101,1405316
2023-12-20 09:30:00,22.260000,22.309999,22.184999,22.209999,22.209999,3810793
2023-12-20 10:30:00,22.215000,22.299999,22.195000,22.290001,22.290001,1896704
2023-12-20 11:30:00,22.290001,22.299900,22.245001,22.250299,22.250299,891798
2023-12-20 12:30:00,22.254999,22.295000,22.230000,22.268999,22.268999,867641
2023-12-20 13:30:00,22.264999,22.290001,22.252899,22.264999,22.264999,654291
2023-12-20 14:30:00,22.260099,22.275101,22.070999,22.105000,22.105000,1802979
2023-12-20 15:30:00,22.110001,22.120001,22.040001,22.045000,22.045000,2075565
2023-12-21 09:30:00,22.280001,22.420000,22.195000,22.305000,22.305000,8293610
2023-12-21 10:30:00,22.305000,22.350000,22.219999,22.329901,22.329901,2202314
2023-12-21 11:30:00,22.330000,22.334999,22.241899,22.250000,22.250000,1168253
2023-12-21 12:30:00,22.250000,22.289900,22.209999,22.245899,22.245899,1259841
2023-12-21 13:30:00,22.250000,22.280001,22.215000,22.275000,22.275000,1012195
2023-12-21 14:30:00,22.280001,22.329500,22.270000,22.299999,22.299999,1157841
2023-12-21 15:30:00,22.295000,22.330000,22.290001,22.309999,22.309999,1602124
2023-12-22 09:30:00,22.410000,22.525200,22.400000,22.420000,22.420000,5112374
2023-12-22 10:30:00,22.419500,22.424999,22.204500,22.270000,22.270000,3407064
2023-12-22 11:30:00,22.270100,22.299999,22.120001,22.235001,22.235001,3083168
2023-12-22 12:30:00,22.240000,22.254999,22.204599,22.240000,22.240000,660672
2023-12-22 13:30:00,22.230000,22.240000,22.049999,22.059999,22.059999,1799458
2023-12-22 14:30:00,22.059999,22.120001,22.049999,22.105000,22.105000,1565207
2023-12-22 15:30:00,22.105000,22.120001,22.100000,22.115000,22.115000,1304862
2023-12-26 09:30:00,22.209999,22.209999,22.040001,22.150000,22.150000,3855088
2023-12-26 10:30:00,22.149900,22.180000,22.134399,22.165001,22.165001,1371116
2023-12-26 11:30:00,22.170000,22.207500,22.150000,22.184999,22.184999,1256743
2023-12-26 12:30:00,22.184999,22.184999,22.065001,22.110001,22.110001,1535342
2023-12-26 13:30:00,22.115000,22.180000,22.110100,22.174999,22.174999,1276713
2023-12-26 14:30:00,22.174999,22.197500,22.160000,22.174999,22.174999,1321174
2023-12-26 15:30:00,22.180000,22.219999,22.170000,22.219999,22.219999,1020043
2023-12-27 09:30:00,22.100000,22.285000,22.090000,22.270000,22.270000,3993637
2023-12-27 10:30:00,22.280001,22.389999,22.260000,22.320000,22.320000,4041557
2023-12-27 11:30:00,22.320000,22.350000,22.290001,22.299999,22.299999,1545673
2023-12-27 12:30:00,22.309900,22.370001,22.290001,22.305000,22.305000,1038454
2023-12-27 13:30:00,22.309900,22.309900,22.186001,22.209900,22.209900,1302016
2023-12-27 14:30:00,22.209999,22.240000,22.180000,22.200001,22.200001,730816
2023-12-27 15:30:00,22.205000,22.240000,22.200001,22.235001,22.235001,734414
2023-12-28 09:30:00,22.170000,22.250000,22.059999,22.218000,22.218000,2689881
2023-12-28 10:30:00,22.219999,22.225000,22.080000,22.115000,22.115000,1723650
2023-12-28 11:30:00,22.113800,22.139999,22.090000,22.105000,22.105000,1115610
2023-12-28 12:30:00,22.109900,22.129999,22.037701,22.070000,22.070000,1973294
2023-12-28 13:30:00,22.070000,22.070000,21.980000,22.000000,22.000000,1049381
2023-12-28 14:30:00,21.995001,22.009899,21.959999,21.999901,21.999901,1112327
2023-12-28 15:30:00,21.995001,22.014999,21.969999,21.983999,21.983999,1184703
2023-12-29 09:30:00,21.620001,21.855301,21.559999,21.855301,21.855301,4177596
2023-12-29 10:30:00,21.860001,21.905001,21.809999,21.865000,21.865000,2570833
2023-12-29 11:30:00,21.861099,21.950001,21.860001,21.934999,21.934999,1338214
2023-12-29 12:30:00,21.940001,21.949900,21.799999,21.805401,21.805401,1401225
2023-12-29 13:30:00,21.799999,21.835300,21.790001,21.815001,21.815001,1817237
2023-12-29 14:30:00,21.809999,21.830000,21.790001,21.795900,21.795900,645145
2023-12-29 15:30:00,21.795000,21.799900,21.760000,21.780001,21.780001,1011242

In [7]:
data_1d = yf.download('SLV', start = '2023-10-23', end = '2024-01-01', interval = '1d')
data_1d

[*********************100%%**********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close    Volume
Date
2023-10-23  21.200001  21.270000  21.000000  21.049999  21.049999  14074100
2023-10-24  20.920000  21.090000  20.860001  21.020000  21.020000  11491700
2023-10-25  20.910000  21.080000  20.670000  20.940001  20.940001  17639800
2023-10-26  20.910000  20.969999  20.570000  20.850000  20.850000  14326600
2023-10-27  20.920000  21.190001  20.760000  21.180000  21.180000  18630000
2023-10-30  21.590000  21.610001  21.230000  21.340000  21.340000  15304600
2023-10-31  21.139999  21.360001  20.840000  20.980000  20.980000  17624900
2023-11-01  20.820000  21.090000  20.660000  20.969999  20.969999  25224400
2023-11-02  21.070000  21.100000  20.770000  20.870001  20.870001  12232500
2023-11-03  21.030001  21.350000  20.990000  21.219999  21.219999  21254500
2023-11-06  21.219999  21.230000  21.070000  21.080000  21.080000  10278200
2023-11-07  20.730000  20.760000  20.570000  20.730000  20.730000  16082200
2023-11-08  20.809999  20.940001  20.620001  20.650000  20.650000  14361200
2023-11-09  20.750000  21.070000  20.650000  20.690001  20.690001  18732000
2023-11-10  20.549999  20.600000  20.340000  20.340000  20.340000  14049800
2023-11-13  20.180000  20.490000  20.100000  20.430000  20.430000  11091100
2023-11-14  20.920000  21.240000  20.870001  21.170000  21.170000  21723900
2023-11-15  21.360001  21.520000  21.240000  21.450001  21.450001  18585600
2023-11-16  21.879999  22.059999  21.730000  21.760000  21.760000  20259200
2023-11-17  21.790001  21.860001  21.680000  21.750000  21.750000  12296000
2023-11-20  21.420000  21.610001  21.379999  21.480000  21.480000   9559600
2023-11-21  21.879999  22.000000  21.740000  21.770000  21.770000  15213000
2023-11-22  21.700001  21.820000  21.570000  21.670000  21.670000  11143900
2023-11-24  22.020000  22.290001  22.000000  22.270000  22.270000  10803300
2023-11-27  22.670000  22.709999  22.500000  22.559999  22.559999  19785600
2023-11-28  22.680000  22.920000  22.590000  22.920000  22.920000  17064400
2023-11-29  22.959999  23.129999  22.820000  22.879999  22.879999  16675200
2023-11-30  22.969999  23.150000  22.850000  23.129999  23.129999  14364300
2023-12-01  23.090000  23.370001  23.049999  23.330000  23.330000  22098300
2023-12-04  22.750000  22.920000  22.360001  22.459999  22.459999  30668300
2023-12-05  22.280001  22.379999  21.950001  22.120001  22.120001  27205100
2023-12-06  22.170000  22.200001  21.870001  21.930000  21.930000  13374500
2023-12-07  21.889999  21.910000  21.600000  21.790001  21.790001  16758500
2023-12-08  21.350000  21.559999  21.020000  21.100000  21.100000  28718900
2023-12-11  20.969999  21.000000  20.809999  20.910000  20.910000  22883700
2023-12-12  20.969999  20.980000  20.780001  20.840000  20.840000  12118700
2023-12-13  20.750000  21.780001  20.610001  21.770000  21.770000  35068000
2023-12-14  21.990000  22.180000  21.990000  22.150000  22.150000  21384100
2023-12-15  21.980000  22.030001  21.750000  21.830000  21.830000  12013400
2023-12-18  21.879999  21.879999  21.660000  21.799999  21.799999  12927400
2023-12-19  21.910000  22.129999  21.889999  22.030001  22.030001  12752700
2023-12-20  22.260000  22.309999  22.040001  22.040001  22.040001  12523600
2023-12-21  22.280001  22.420000  22.200001  22.309999  22.309999  17063600
2023-12-22  22.410000  22.530001  22.049999  22.120001  22.120001  17222200
2023-12-26  22.209999  22.219999  22.040001  22.200001  22.200001  11861700
2023-12-27  22.100000  22.400000  22.090000  22.230000  22.230000  13898400
2023-12-28  22.170000  22.250000  21.959999  21.990000  21.990000  11257800
2023-12-29  21.620001  21.950001  21.559999  21.780001  21.780001  13151200

In [8]:
print(len(data_5m))
print(len(data_15m))
print(len(data_30m))
print(len(data_60m))
print(len(data_1d))

1560
520
260
140
48

In [9]:
#note: data_1d starts 28 days before the time of data_5m data

In [10]:
rsis_5m = talib.RSI(data_5m['Close'], timeperiod=14)
rsis_15m = talib.RSI(data_15m['Close'], timeperiod=14)
rsis_30m = talib.RSI(data_30m['Close'], timeperiod=14)
rsis_60m = talib.RSI(data_60m['Close'], timeperiod=14)

In [11]:
rsis_5m

Datetime
2023-12-01 09:30:00-05:00          NaN
2023-12-01 09:35:00-05:00          NaN
2023-12-01 09:40:00-05:00          NaN
2023-12-01 09:45:00-05:00          NaN
2023-12-01 09:50:00-05:00          NaN
                               ...
2023-12-29 15:35:00-05:00    32.768381
2023-12-29 15:40:00-05:00    31.098662
2023-12-29 15:45:00-05:00    29.481488
2023-12-29 15:50:00-05:00    26.511549
2023-12-29 15:55:00-05:00    33.703900
Length: 1560, dtype: float64

In [12]:
rsis_1d = talib.RSI(data_1d['Close'], timeperiod=14)

In [13]:
rsis_1d

Date
2023-10-23          NaN
2023-10-24          NaN
2023-10-25          NaN
2023-10-26          NaN
2023-10-27          NaN
2023-10-30          NaN
2023-10-31          NaN
2023-11-01          NaN
2023-11-02          NaN
2023-11-03          NaN
2023-11-06          NaN
2023-11-07          NaN
2023-11-08          NaN
2023-11-09          NaN
2023-11-10    35.627534
2023-11-13    38.058146
2023-11-14    53.578662
2023-11-15    57.879272
2023-11-16    62.069064
2023-11-17    61.855313
2023-11-20    56.225374
2023-11-21    60.394993
2023-11-22    58.331679
2023-11-24    65.866597
2023-11-27    68.802996
2023-11-28    72.020817
2023-11-29    71.142744
2023-11-30    73.331169
2023-12-01    74.966744
2023-12-04    58.235540
2023-12-05    53.235204
2023-12-06    50.619482
2023-12-07    48.719913
2023-12-08    40.627694
2023-12-11    38.720512
2023-12-12    38.012528
2023-12-13    50.866354
2023-12-14    54.974720
2023-12-15    51.099815
2023-12-18    50.738734
2023-12-19    53.454229
2023-12-20    53.574060
2023-12-21    56.807276
2023-12-22    53.959439
2023-12-26    54.982764
2023-12-27    55.383234
2023-12-28    51.440578
2023-12-29    48.206800
dtype: float64

In [14]:
rsismas_5m = talib.SMA(rsis_5m, timeperiod=14)
rsismas_15m = talib.SMA(rsis_15m, timeperiod=14)
rsismas_30m = talib.SMA(rsis_30m, timeperiod=14)
rsismas_60m = talib.SMA(rsis_60m, timeperiod=14)

In [15]:
rsismas_5m

Datetime
2023-12-01 09:30:00-05:00          NaN
2023-12-01 09:35:00-05:00          NaN
2023-12-01 09:40:00-05:00          NaN
2023-12-01 09:45:00-05:00          NaN
2023-12-01 09:50:00-05:00          NaN
                               ...
2023-12-29 15:35:00-05:00    39.855787
2023-12-29 15:40:00-05:00    39.253375
2023-12-29 15:45:00-05:00    38.535451
2023-12-29 15:50:00-05:00    37.287661
2023-12-29 15:55:00-05:00    36.553611
Length: 1560, dtype: float64

In [16]:
rsismas_1d = talib.SMA(rsis_1d, timeperiod=14)

In [17]:
rsismas_1d

Date
2023-10-23          NaN
2023-10-24          NaN
2023-10-25          NaN
2023-10-26          NaN
2023-10-27          NaN
2023-10-30          NaN
2023-10-31          NaN
2023-11-01          NaN
2023-11-02          NaN
2023-11-03          NaN
2023-11-06          NaN
2023-11-07          NaN
2023-11-08          NaN
2023-11-09          NaN
2023-11-10          NaN
2023-11-13          NaN
2023-11-14          NaN
2023-11-15          NaN
2023-11-16          NaN
2023-11-17          NaN
2023-11-20          NaN
2023-11-21          NaN
2023-11-22          NaN
2023-11-24          NaN
2023-11-27          NaN
2023-11-28          NaN
2023-11-29          NaN
2023-11-30    59.656026
2023-12-01    62.465969
2023-12-04    63.907212
2023-12-05    63.882679
2023-12-06    63.364122
2023-12-07    62.410612
2023-12-08    60.894353
2023-12-11    59.644006
2023-12-12    58.045258
2023-12-13    57.512021
2023-12-14    56.734030
2023-12-15    55.469517
2023-12-18    53.949368
2023-12-19    52.685903
2023-12-20    51.274681
2023-12-21    49.977576
2023-12-22    49.672140
2023-12-26    49.796966
2023-12-27    50.137234
2023-12-28    50.331567
2023-12-29    50.872932
dtype: float64

In [18]:
datetime_list = data_5m.index.tolist()

In [19]:
datetime_list[0]
print(rsis_1d[28])
print(rsismas_1d[28])

74.96674355735918
62.46596918503676

In [20]:
print(len(rsis_5m))
print(len(rsis_15m))
print(len(rsis_30m))
print(len(rsis_60m))
print(len(rsis_1d))

1560
520
260
140
48

In [21]:
class Event:
    def __init__(self, date, close, rsi_5m, rsisma_5m, rsi_15m, rsisma_15m, 
                 rsi_30m, rsisma_30m, rsi_60m, rsisma_60m, rsi_1d, rsisma_1d):
        self.date = date
        self.close = close
        self.rsi_5m = rsi_5m
        self.rsisma_5m = rsisma_5m
        self.ratio_5m = rsi_5m / rsisma_5m
        self.rsi_15m = rsi_15m
        self.rsisma_15m = rsisma_15m
        self.ratio_15m = rsi_15m / rsisma_15m
        self.rsi_30m = rsi_30m
        self.rsisma_30m = rsisma_30m
        self.ratio_30m = rsi_30m / rsisma_30m
        self.rsi_60m = rsi_60m
        self.rsisma_60m = rsisma_60m
        self.ratio_60m = rsi_60m / rsisma_60m
        self.rsi_1d = rsi_1d
        self.rsisma_1d = rsisma_1d
        self.ratio_1d = rsi_1d / rsisma_1d

events = [Event(datetime_list[0], data_5m['Close'].get(0), rsis_5m.iloc[0], rsismas_5m.iloc[0], rsis_15m.iloc[0], 
                rsismas_15m.iloc[0], rsis_30m.iloc[0], rsismas_30m.iloc[0], rsis_60m.iloc[0], rsismas_60m.iloc[0],
               rsis_1d.iloc[27], rsismas_1d.iloc[27])]

#rsis_5m: rsi at 15:45 means rsi value at 15:50
#rsis_15m: rsi at 14:45 means rsi value at 15:00
#rsis_30m: rsi at 14:30 means rsi value at 15:00
#rsis_60m: rsi at 14:30 means rsi value at 15:30

rsi_15_counter = -2
rsi_30_counter = -5
rsi_1h_counter = -11
rsi_1d_counter = 1;

for num in range(1, data_5m.shape[0]):
    current_rsi_15m = rsis_15m[int((rsi_15_counter / 3))]
    current_rsisma_15m = rsismas_15m[int((rsi_15_counter / 3))]
    current_rsi_30m = rsis_30m[int((rsi_30_counter / 6))]
    current_rsisma_30m = rsismas_30m[int((rsi_30_counter / 6))]
    current_rsi_60m = rsis_60m[int((rsi_1h_counter / 12)) + 1]
    current_rsisma_60m = rsismas_60m[int((rsi_1h_counter / 12)) + 2]
    current_rsi_1d = rsis_1d[int((rsi_1d_counter / 78)) + 27]
    current_rsisma_1d = rsismas_1d[int((rsi_1d_counter / 78)) + 27]
    
    currentEvent = Event(datetime_list[num], data_5m['Close'].get(num), rsis_5m.iloc[num - 1], 
                         rsismas_5m.iloc[num - 1], current_rsi_15m, current_rsisma_15m, current_rsi_30m,
                        current_rsisma_30m, current_rsi_60m, current_rsisma_60m, current_rsi_1d,
                        current_rsisma_1d)
    
    rsi_15_counter += 1
    rsi_30_counter += 1
    rsi_1h_counter += 1
    rsi_1d_counter += 1
    events.append(currentEvent)

#note to self: rsisma_60m starts at index 312

In [22]:
print(events[data_5m.shape[0] - 1].date)
print(events[data_5m.shape[0] - 1].rsi_5m)

2023-12-29 15:55:00-05:00
26.511548862328404

In [23]:
def calculate_average(lst):
    if len(lst) == 0:
        return 0  # Handle the case where the list is empty to avoid division by zero error
    total = sum(lst)
    average = total / len(lst)
    return average

In [24]:
class ratio_profit:
    def __init__(self, entry_ratio, ratio, profit, num_trades, win_rate, average_profit, average_loss,
                greatest_profit, greatest_loss):
        self.entry_ratio = entry_ratio
        self.ratio = ratio
        self.profit = profit
        self.num_trades = num_trades
        self.win_rate = win_rate
        self.average_profit = average_profit
        self.average_loss = average_loss
        self.greatest_profit = greatest_profit
        self.greatest_loss = greatest_loss

ratio_profits = []

entry_ratio_values = np.arange(0.900, 1.100, 0.001)
ratio_values = np.arange(1.000, 1.200, 0.001)

for entry_ratio in entry_ratio_values:
    for ratio in ratio_values:
        entryIndices = []
        exitIndices = []
        trade_counter = 0
        holding_position = False
        all_profits = []
        all_losses = []
        
        for i in range(313, data_5m.shape[0]):
            min_ratio_prev = min([events[i-1].ratio_5m, events[i-1].ratio_15m, 
                                         events[i-1].ratio_30m, events[i-1].ratio_60m, events[i-1].ratio_1d])
            if holding_position == False:
                if min_ratio_prev >= entry_ratio:
                    entryIndices.append(i)
                    holding_position = True
            elif holding_position == True:
                if min_ratio_prev < ratio and events[i - 1].ratio_60m < events[i - 2].ratio_60m:
                    exitIndices.append(i)
                    trade_counter += 1
                    holding_position = False
        
        profit_multiplier = 1.00
        wins = 0
        win_rate = 0
        
        for date in range(0, len(exitIndices)):
            profit = events[exitIndices[date]].close / events[entryIndices[date]].close
            profit_multiplier *= profit
            if profit > 1.00:
                wins += 1
                all_profits.append(profit)
            else:
                all_losses.append(profit)
        if trade_counter != 0:
            win_rate = wins / trade_counter
        elif trade_counter == 0:
            win_rate = 0
        
        average_profit = 0
        average_loss = 0
        greatest_profit = 0
        greatest_loss = 0
        
        if len(all_profits) == 0:
            average_profit = 0
            greatest_profit = 0
        else:
            average_profit = calculate_average(all_profits)
            greatest_profit = max(all_profits)
        
        if len(all_losses) == 0:
            average_loss = 0
            greatest_loss = 0
        else:
            average_loss = calculate_average(all_losses)
            greatest_loss = min(all_losses)
        
        rp = ratio_profit(entry_ratio, ratio, profit_multiplier, trade_counter, win_rate,
                         average_profit, average_loss, greatest_profit, greatest_loss)
        
        if (trade_counter < 25):
            ratio_profits.append(rp)

max_profit_index = 0
for i in range(1, len(ratio_profits)):
    if ratio_profits[i].profit > ratio_profits[max_profit_index].profit:
        max_profit_index = i

print("entry ratio: ", ratio_profits[max_profit_index].entry_ratio)
print("ratio: ", ratio_profits[max_profit_index].ratio)
print("profit: ", ratio_profits[max_profit_index].profit)
print("num_trades: ", ratio_profits[max_profit_index].num_trades)
print("win_rate: ", ratio_profits[max_profit_index].win_rate)
print("average_profit: ", ratio_profits[max_profit_index].average_profit)
print("average_loss: ", ratio_profits[max_profit_index].average_loss)
print("greatest_profit: ", ratio_profits[max_profit_index].greatest_profit)
print("greatest_loss: ", ratio_profits[max_profit_index].greatest_loss)

entry ratio:  1.0150000000000001
ratio:  1.0
profit:  1.0
num_trades:  0
win_rate:  0
average_profit:  0
average_loss:  0
greatest_profit:  0
greatest_loss:  0